// Codigos de error de la revision administrativa (SPEC 006, 11).

export enum QuestionReviewErrorCode {
  REVIEW_NOT_FOUND = 'QUESTION_REVIEW_NOT_FOUND',
  INVALID_ACTION = 'QUESTION_REVIEW_INVALID_ACTION',
  VALIDATION_REQUIRED = 'QUESTION_REVIEW_VALIDATION_REQUIRED',
  APPROVAL_BLOCKED = 'QUESTION_REVIEW_APPROVAL_BLOCKED',
  NOTES_REQUIRED = 'QUESTION_REVIEW_NOTES_REQUIRED',
  INVALID_STATUS_TRANSITION = 'QUESTION_REVIEW_INVALID_STATUS_TRANSITION',
  OBSOLETE_CANNOT_BE_VALIDATED = 'QUESTION_OBSOLETE_CANNOT_BE_VALIDATED',
  REJECTED_REQUIRES_REVIEW_REOPEN = 'QUESTION_REJECTED_REQUIRES_REVIEW_REOPEN',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
}
