// Codigos de error de la realizacion y correccion de tests (SPEC 008, 11).

export enum TestAttemptErrorCode {
  TEST_NOT_FOUND = 'TEST_NOT_FOUND',
  TEST_CANCELLED_CANNOT_BE_STARTED = 'TEST_CANCELLED_CANNOT_BE_STARTED',
  ATTEMPT_NOT_FOUND = 'TEST_ATTEMPT_NOT_FOUND',
  ALREADY_SUBMITTED = 'TEST_ATTEMPT_ALREADY_SUBMITTED',
  CANCELLED = 'TEST_ATTEMPT_CANCELLED',
  QUESTION_NOT_IN_TEST = 'QUESTION_NOT_IN_TEST',
  OPTION_NOT_IN_QUESTION = 'OPTION_NOT_IN_QUESTION',
  REVIEW_NOT_AVAILABLE = 'TEST_ATTEMPT_REVIEW_NOT_AVAILABLE',
  INVALID_STATUS = 'TEST_ATTEMPT_INVALID_STATUS',
}
