// Errores del constructor de indice de temario (SPEC 019, 27).

export enum SyllabusIndexErrorCode {
  ACCESS_DENIED = 'SYLLABUS_INDEX_ACCESS_DENIED',
  OPPOSITION_REQUIRED = 'SYLLABUS_INDEX_OPPOSITION_REQUIRED',
  OPPOSITION_NOT_FOUND = 'SYLLABUS_INDEX_OPPOSITION_NOT_FOUND',
  NO_MATERIALS = 'SYLLABUS_INDEX_NO_MATERIALS',
  NO_EXTRACTED_TEXT = 'SYLLABUS_INDEX_NO_EXTRACTED_TEXT',
  TOO_MUCH_INPUT = 'SYLLABUS_INDEX_TOO_MUCH_INPUT',
  PROVIDER_NOT_CONFIGURED = 'SYLLABUS_INDEX_PROVIDER_NOT_CONFIGURED',
  GENERATION_FAILED = 'SYLLABUS_INDEX_GENERATION_FAILED',
  INVALID_OUTPUT = 'SYLLABUS_INDEX_INVALID_OUTPUT',
  PROPOSAL_NOT_FOUND = 'SYLLABUS_INDEX_PROPOSAL_NOT_FOUND',
  PROPOSAL_ALREADY_APPLIED = 'SYLLABUS_INDEX_PROPOSAL_ALREADY_APPLIED',
  APPROVAL_REQUIRED = 'SYLLABUS_INDEX_APPROVAL_REQUIRED',
  APPLY_FAILED = 'SYLLABUS_INDEX_APPLY_FAILED',
  TOPIC_DUPLICATE_SKIPPED = 'SYLLABUS_INDEX_TOPIC_DUPLICATE_SKIPPED',
  NODE_NOT_FOUND = 'SYLLABUS_INDEX_NODE_NOT_FOUND',
  PROPOSAL_NOT_EDITABLE = 'SYLLABUS_INDEX_PROPOSAL_NOT_EDITABLE',
}

export class SyllabusIndexError extends Error {
  readonly codes: SyllabusIndexErrorCode[];

  constructor(codes: SyllabusIndexErrorCode[], message?: string) {
    super(message ?? codes.join(', '));
    this.name = 'SyllabusIndexError';
    this.codes = codes;
  }
}
