// Checks puros de la compuerta de calidad (SPEC 005): validacion formal,
// señales de ambiguedad/calidad e info. No acceden a repositorios; la
// resolucion de fuente/tema/duplicados (que necesita repos) la hace el servicio.

import { DIFFICULTIES, QUESTION_STATUSES } from '../models/enums.js';
import type { Option } from '../models/option.js';
import type { Question } from '../models/question.js';
import { normalizeOptionText } from '../validation/normalizeOptionText.js';
import {
  makeFinding,
  QuestionValidationCode,
  type Finding,
} from './qualityCodes.js';

export const STATEMENT_MIN_LENGTH = 15;
export const EXPLANATION_MIN_LENGTH = 20;

// Validacion formal: estructura minima (SPEC 005, 7.1 + 7.4). Solo errores.
export function formalFindings(question: Question): Finding[] {
  const findings: Finding[] = [];
  const options = question.options ?? [];

  if (!isNonEmptyString(question.statement)) {
    findings.push(makeFinding(QuestionValidationCode.STATEMENT_REQUIRED));
  }

  if (options.length === 0) {
    findings.push(makeFinding(QuestionValidationCode.OPTIONS_REQUIRED));
  } else if (options.length < 2) {
    findings.push(makeFinding(QuestionValidationCode.MIN_OPTIONS_NOT_MET));
  }

  if (options.length > 0) {
    if (options.filter((option) => option.is_correct).length !== 1) {
      findings.push(
        makeFinding(QuestionValidationCode.SINGLE_CORRECT_OPTION_REQUIRED),
      );
    }
    const ids = options.map((option) => option.id);
    if (question.correct_answer && !ids.includes(question.correct_answer)) {
      findings.push(
        makeFinding(QuestionValidationCode.CORRECT_OPTION_NOT_FOUND),
      );
    }
    if (hasDuplicateOptions(options)) {
      findings.push(makeFinding(QuestionValidationCode.DUPLICATE_OPTIONS));
    }
  }

  if (!isNonEmptyString(question.explanation)) {
    findings.push(makeFinding(QuestionValidationCode.EXPLANATION_REQUIRED));
  }

  if (!question.source) {
    findings.push(makeFinding(QuestionValidationCode.SOURCE_REQUIRED));
  }

  if (!isNonEmptyString(question.topic) && !isNonEmptyString(question.topic_id)) {
    findings.push(makeFinding(QuestionValidationCode.TOPIC_REQUIRED));
  }

  if (question.difficulty === null || question.difficulty === undefined) {
    findings.push(makeFinding(QuestionValidationCode.DIFFICULTY_REQUIRED));
  } else if (!DIFFICULTIES.includes(question.difficulty)) {
    findings.push(makeFinding(QuestionValidationCode.INVALID_DIFFICULTY));
  }

  if (!QUESTION_STATUSES.includes(question.status)) {
    findings.push(makeFinding(QuestionValidationCode.INVALID_STATUS));
  }

  return findings;
}

// Señales simples de ambiguedad/baja calidad (SPEC 005, 7.6). Solo warnings.
export function ambiguityFindings(question: Question): Finding[] {
  const findings: Finding[] = [];
  const statement = (question.statement ?? '').trim();
  const explanation = (question.explanation ?? '').trim();
  const options = question.options ?? [];

  if (statement.length > 0 && statement.length < STATEMENT_MIN_LENGTH) {
    findings.push(makeFinding(QuestionValidationCode.STATEMENT_TOO_SHORT));
  }

  if (explanation.length > 0 && explanation.length < EXPLANATION_MIN_LENGTH) {
    findings.push(makeFinding(QuestionValidationCode.EXPLANATION_TOO_SHORT));
  }

  if (/\b(excepto|salvo|incorrect[ao]|fals[ao])\b/i.test(statement)) {
    findings.push(makeFinding(QuestionValidationCode.NEGATIVE_WORDING_REVIEW));
  }

  if (
    /\b(podr[ií]a|quiz[áa]s?|a veces|generalmente|normalmente|depende|posiblemente)\b/i.test(
      statement,
    )
  ) {
    findings.push(
      makeFinding(QuestionValidationCode.STATEMENT_POSSIBLY_AMBIGUOUS),
    );
  }

  if (
    options.some((option) =>
      /todas las anteriores|ninguna de las anteriores|todas las opciones|ninguna de las opciones/i.test(
        option.text,
      ),
    )
  ) {
    findings.push(
      makeFinding(QuestionValidationCode.ALL_OR_NONE_OPTION_REVIEW),
    );
  }

  if (optionsTooSimilar(options)) {
    findings.push(makeFinding(QuestionValidationCode.OPTIONS_TOO_SIMILAR));
  }

  return findings;
}

// Info de contexto (SPEC 005, 8). Solo info.
export function infoFindings(question: Question): Finding[] {
  const findings: Finding[] = [];
  if (question.generation_metadata) {
    findings.push(makeFinding(QuestionValidationCode.INFO_AUTOGENERATED));
  }
  return findings;
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0;
}

function hasDuplicateOptions(options: Option[]): boolean {
  const seen = new Set<string>();
  for (const option of options) {
    const key = normalizeOptionText(option.text);
    if (seen.has(key)) {
      return true;
    }
    seen.add(key);
  }
  return false;
}

// Dos opciones son "demasiado parecidas" si, sin ser identicas (eso seria
// duplicado), una contiene textualmente a la otra tras normalizar.
function optionsTooSimilar(options: Option[]): boolean {
  const normalized = options.map((option) => normalizeOptionText(option.text));
  for (let i = 0; i < normalized.length; i++) {
    for (let j = i + 1; j < normalized.length; j++) {
      const a = normalized[i];
      const b = normalized[j];
      if (a && b && a !== b && (a.includes(b) || b.includes(a))) {
        return true;
      }
    }
  }
  return false;
}
