// Codigos de hallazgo de la compuerta de calidad (SPEC 005). Incluye errores
// (bloquean el avance), advertencias (exigen revision) e info (contexto util).
// Cada codigo tiene una severidad y un mensaje por defecto en el catalogo.

export type Severity = 'error' | 'warning' | 'info';

export enum QuestionValidationCode {
  // --- Errores: validacion formal (SPEC 005, 7.1) ---
  STATEMENT_REQUIRED = 'QUESTION_STATEMENT_REQUIRED',
  OPTIONS_REQUIRED = 'QUESTION_OPTIONS_REQUIRED',
  MIN_OPTIONS_NOT_MET = 'QUESTION_MIN_OPTIONS_NOT_MET',
  SINGLE_CORRECT_OPTION_REQUIRED = 'QUESTION_SINGLE_CORRECT_OPTION_REQUIRED',
  CORRECT_OPTION_NOT_FOUND = 'QUESTION_CORRECT_OPTION_NOT_FOUND',
  EXPLANATION_REQUIRED = 'QUESTION_EXPLANATION_REQUIRED',
  SOURCE_REQUIRED = 'QUESTION_SOURCE_REQUIRED',
  TOPIC_REQUIRED = 'QUESTION_TOPIC_REQUIRED',
  DIFFICULTY_REQUIRED = 'QUESTION_DIFFICULTY_REQUIRED',
  INVALID_DIFFICULTY = 'QUESTION_INVALID_DIFFICULTY',
  INVALID_STATUS = 'QUESTION_INVALID_STATUS',
  DUPLICATE_OPTIONS = 'QUESTION_DUPLICATE_OPTIONS',
  // --- Errores: fuente (SPEC 005, 7.2) ---
  SOURCE_NOT_FOUND = 'QUESTION_SOURCE_NOT_FOUND',
  SOURCE_MATERIAL_NOT_FOUND = 'QUESTION_SOURCE_MATERIAL_NOT_FOUND',
  SOURCE_OBSOLETE = 'QUESTION_SOURCE_OBSOLETE',
  SOURCE_MATERIAL_OBSOLETE = 'QUESTION_SOURCE_MATERIAL_OBSOLETE',
  // --- Errores: tema (SPEC 005, 7.3) ---
  TOPIC_NOT_FOUND = 'QUESTION_TOPIC_NOT_FOUND',
  TOPIC_OBSOLETE = 'QUESTION_TOPIC_OBSOLETE',
  // --- Errores: duplicados (SPEC 005, 7.5) ---
  DUPLICATE_STATEMENT = 'QUESTION_DUPLICATE_STATEMENT',
  // --- Advertencias: fuente (SPEC 005, 7.2, MVP) ---
  SOURCE_REFERENCE_MISSING = 'QUESTION_SOURCE_REFERENCE_MISSING',
  SOURCE_EXCERPT_MISSING = 'QUESTION_SOURCE_EXCERPT_MISSING',
  // --- Advertencias: ambiguedad/calidad (SPEC 005, 7.6) ---
  STATEMENT_TOO_SHORT = 'QUESTION_STATEMENT_TOO_SHORT',
  STATEMENT_POSSIBLY_AMBIGUOUS = 'QUESTION_STATEMENT_POSSIBLY_AMBIGUOUS',
  EXPLANATION_TOO_SHORT = 'QUESTION_EXPLANATION_TOO_SHORT',
  OPTIONS_TOO_SIMILAR = 'QUESTION_OPTIONS_TOO_SIMILAR',
  NEGATIVE_WORDING_REVIEW = 'QUESTION_NEGATIVE_WORDING_REVIEW',
  ALL_OR_NONE_OPTION_REVIEW = 'QUESTION_ALL_OR_NONE_OPTION_REVIEW',
  // --- Info (SPEC 005, 8) ---
  INFO_AUTOGENERATED = 'QUESTION_INFO_AUTOGENERATED',
  INFO_SOURCE_LINKED = 'QUESTION_INFO_SOURCE_LINKED',
}

export interface Finding {
  code: QuestionValidationCode;
  severity: Severity;
  message: string;
}

export const FINDING_CATALOG: Record<
  QuestionValidationCode,
  { severity: Severity; message: string }
> = {
  [QuestionValidationCode.STATEMENT_REQUIRED]: {
    severity: 'error',
    message: 'La pregunta no tiene enunciado.',
  },
  [QuestionValidationCode.OPTIONS_REQUIRED]: {
    severity: 'error',
    message: 'La pregunta no tiene opciones.',
  },
  [QuestionValidationCode.MIN_OPTIONS_NOT_MET]: {
    severity: 'error',
    message: 'La pregunta tiene menos de 2 opciones.',
  },
  [QuestionValidationCode.SINGLE_CORRECT_OPTION_REQUIRED]: {
    severity: 'error',
    message: 'La pregunta no tiene exactamente una opcion correcta.',
  },
  [QuestionValidationCode.CORRECT_OPTION_NOT_FOUND]: {
    severity: 'error',
    message: 'La respuesta correcta no existe entre las opciones.',
  },
  [QuestionValidationCode.EXPLANATION_REQUIRED]: {
    severity: 'error',
    message: 'La pregunta no tiene explicacion.',
  },
  [QuestionValidationCode.SOURCE_REQUIRED]: {
    severity: 'error',
    message: 'La pregunta no tiene fuente.',
  },
  [QuestionValidationCode.TOPIC_REQUIRED]: {
    severity: 'error',
    message: 'La pregunta no tiene tema (ni texto ni topic_id).',
  },
  [QuestionValidationCode.DIFFICULTY_REQUIRED]: {
    severity: 'error',
    message: 'La pregunta no tiene dificultad.',
  },
  [QuestionValidationCode.INVALID_DIFFICULTY]: {
    severity: 'error',
    message: 'La dificultad no es valida (easy, medium o hard).',
  },
  [QuestionValidationCode.INVALID_STATUS]: {
    severity: 'error',
    message: 'El estado de la pregunta no es valido.',
  },
  [QuestionValidationCode.DUPLICATE_OPTIONS]: {
    severity: 'error',
    message: 'La pregunta tiene opciones duplicadas.',
  },
  [QuestionValidationCode.SOURCE_NOT_FOUND]: {
    severity: 'error',
    message: 'No se encuentra la fuente de la pregunta.',
  },
  [QuestionValidationCode.SOURCE_MATERIAL_NOT_FOUND]: {
    severity: 'error',
    message: 'El material vinculado a la fuente no existe.',
  },
  [QuestionValidationCode.SOURCE_OBSOLETE]: {
    severity: 'error',
    message: 'La fuente esta marcada como obsoleta.',
  },
  [QuestionValidationCode.SOURCE_MATERIAL_OBSOLETE]: {
    severity: 'error',
    message: 'El material vinculado a la fuente esta obsoleto.',
  },
  [QuestionValidationCode.TOPIC_NOT_FOUND]: {
    severity: 'error',
    message: 'El tema vinculado (topic_id) no existe.',
  },
  [QuestionValidationCode.TOPIC_OBSOLETE]: {
    severity: 'error',
    message: 'El tema vinculado esta obsoleto.',
  },
  [QuestionValidationCode.DUPLICATE_STATEMENT]: {
    severity: 'error',
    message: 'Existe otra pregunta con el mismo enunciado.',
  },
  [QuestionValidationCode.SOURCE_REFERENCE_MISSING]: {
    severity: 'warning',
    message: 'La fuente no indica referencia.',
  },
  [QuestionValidationCode.SOURCE_EXCERPT_MISSING]: {
    severity: 'warning',
    message: 'La fuente no incluye fragmento (excerpt).',
  },
  [QuestionValidationCode.STATEMENT_TOO_SHORT]: {
    severity: 'warning',
    message: 'El enunciado es muy corto.',
  },
  [QuestionValidationCode.STATEMENT_POSSIBLY_AMBIGUOUS]: {
    severity: 'warning',
    message: 'El enunciado usa expresiones posiblemente ambiguas.',
  },
  [QuestionValidationCode.EXPLANATION_TOO_SHORT]: {
    severity: 'warning',
    message: 'La explicacion es muy corta.',
  },
  [QuestionValidationCode.OPTIONS_TOO_SIMILAR]: {
    severity: 'warning',
    message: 'Hay opciones demasiado parecidas entre si.',
  },
  [QuestionValidationCode.NEGATIVE_WORDING_REVIEW]: {
    severity: 'warning',
    message: 'El enunciado usa redaccion negativa; revisar.',
  },
  [QuestionValidationCode.ALL_OR_NONE_OPTION_REVIEW]: {
    severity: 'warning',
    message: 'Hay opciones tipo "todas/ninguna de las anteriores"; revisar.',
  },
  [QuestionValidationCode.INFO_AUTOGENERATED]: {
    severity: 'info',
    message: 'Pregunta generada automaticamente.',
  },
  [QuestionValidationCode.INFO_SOURCE_LINKED]: {
    severity: 'info',
    message: 'Fuente vinculada a material activo.',
  },
};

export function makeFinding(code: QuestionValidationCode): Finding {
  const entry = FINDING_CATALOG[code];
  return { code, severity: entry.severity, message: entry.message };
}
