// Codigos de error de validacion definidos por la SPEC 001 (seccion 8).
// Los valores de cadena son contractuales: deben coincidir exactamente con
// los codigos de la spec para que cualquier capa superior (API, panel, IA)
// pueda depender de ellos.

export enum ValidationErrorCode {
  STATEMENT_REQUIRED = 'QUESTION_STATEMENT_REQUIRED',
  OPTIONS_REQUIRED = 'QUESTION_OPTIONS_REQUIRED',
  MIN_OPTIONS_NOT_MET = 'QUESTION_MIN_OPTIONS_NOT_MET',
  SINGLE_CORRECT_OPTION_REQUIRED = 'QUESTION_SINGLE_CORRECT_OPTION_REQUIRED',
  EXPLANATION_REQUIRED = 'QUESTION_EXPLANATION_REQUIRED',
  SOURCE_REQUIRED = 'QUESTION_SOURCE_REQUIRED',
  TOPIC_REQUIRED = 'QUESTION_TOPIC_REQUIRED',
  DIFFICULTY_REQUIRED = 'QUESTION_DIFFICULTY_REQUIRED',
  INVALID_DIFFICULTY = 'QUESTION_INVALID_DIFFICULTY',
  INVALID_STATUS = 'QUESTION_INVALID_STATUS',
  DUPLICATE_OPTIONS = 'QUESTION_DUPLICATE_OPTIONS',
  SOURCE_OBSOLETE = 'QUESTION_SOURCE_OBSOLETE',
  OBSOLETE_CANNOT_BE_VALIDATED = 'QUESTION_OBSOLETE_CANNOT_BE_VALIDATED',
  // SPEC 002: la fuente apunta a un material registrado en estado `obsolete`.
  SOURCE_MATERIAL_OBSOLETE = 'QUESTION_SOURCE_MATERIAL_OBSOLETE',
  // SPEC 003: la pregunta esta vinculada a un tema en estado `obsolete`.
  TOPIC_OBSOLETE = 'QUESTION_TOPIC_OBSOLETE',
}
