// Codigos de error del mapa del temario (SPEC 003, seccion 13).
// Los valores de cadena son contractuales y deben coincidir con la spec.

export enum TopicValidationErrorCode {
  TITLE_REQUIRED = 'TOPIC_TITLE_REQUIRED',
  INVALID_STATUS = 'TOPIC_INVALID_STATUS',
  PARENT_NOT_FOUND = 'TOPIC_PARENT_NOT_FOUND',
  CANNOT_BE_OWN_PARENT = 'TOPIC_CANNOT_BE_OWN_PARENT',
  HIERARCHY_CYCLE_DETECTED = 'TOPIC_HIERARCHY_CYCLE_DETECTED',
  TOPIC_NOT_FOUND = 'TOPIC_NOT_FOUND',
  MATERIAL_NOT_FOUND = 'MATERIAL_NOT_FOUND',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  MATERIAL_LINK_ALREADY_EXISTS = 'TOPIC_MATERIAL_LINK_ALREADY_EXISTS',
}
