// Codigos de error del generador de tests (SPEC 007, seccion 12).

export enum TestGenerationErrorCode {
  QUESTION_COUNT_REQUIRED = 'TEST_QUESTION_COUNT_REQUIRED',
  INVALID_QUESTION_COUNT = 'TEST_INVALID_QUESTION_COUNT',
  MAX_QUESTION_COUNT_EXCEEDED = 'TEST_MAX_QUESTION_COUNT_EXCEEDED',
  TOPIC_NOT_FOUND = 'TEST_TOPIC_NOT_FOUND',
  TOPIC_OBSOLETE = 'TEST_TOPIC_OBSOLETE',
  INVALID_DIFFICULTY = 'TEST_INVALID_DIFFICULTY',
  INVALID_MODE = 'TEST_INVALID_MODE',
  NOT_ENOUGH_VALIDATED_QUESTIONS = 'TEST_NOT_ENOUGH_VALIDATED_QUESTIONS',
  DUPLICATE_QUESTION_NOT_ALLOWED = 'TEST_DUPLICATE_QUESTION_NOT_ALLOWED',
  ONLY_VALIDATED_QUESTIONS_ALLOWED = 'TEST_ONLY_VALIDATED_QUESTIONS_ALLOWED',
}

export const MIN_TEST_QUESTION_COUNT = 1;
export const MAX_TEST_QUESTION_COUNT = 100;
export const DEFAULT_TEST_QUESTION_COUNT = 20;
