// Codigos de error de usuarios, oposiciones y control de acceso (SPEC 010, 16).

export enum AccessErrorCode {
  // Usuario
  USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_PASSWORD_REQUIRED = 'USER_PASSWORD_REQUIRED',
  USER_INVALID_ROLE = 'USER_INVALID_ROLE',
  USER_INVALID_STATUS = 'USER_INVALID_STATUS',
  // Autenticacion / acceso
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  ADMIN_ACCESS_REQUIRED = 'ADMIN_ACCESS_REQUIRED',
  STUDENT_ACCESS_REQUIRED = 'STUDENT_ACCESS_REQUIRED',
  // Oposicion
  OPPOSITION_TITLE_REQUIRED = 'OPPOSITION_TITLE_REQUIRED',
  OPPOSITION_SLUG_REQUIRED = 'OPPOSITION_SLUG_REQUIRED',
  OPPOSITION_SLUG_ALREADY_EXISTS = 'OPPOSITION_SLUG_ALREADY_EXISTS',
  OPPOSITION_INVALID_STATUS = 'OPPOSITION_INVALID_STATUS',
  OPPOSITION_NOT_FOUND = 'OPPOSITION_NOT_FOUND',
  // Acceso a oposicion
  OPPOSITION_ACCESS_NOT_FOUND = 'OPPOSITION_ACCESS_NOT_FOUND',
  OPPOSITION_ACCESS_ALREADY_EXISTS = 'OPPOSITION_ACCESS_ALREADY_EXISTS',
  OPPOSITION_ACCESS_REVOKED = 'OPPOSITION_ACCESS_REVOKED',
  // Integridad de datos por oposicion
  OPPOSITION_REQUIRED = 'OPPOSITION_REQUIRED',
  OPPOSITION_ENTITY_MISMATCH = 'OPPOSITION_ENTITY_MISMATCH',
  // Workspaces y planes (SPEC 011)
  WORKSPACE_NAME_REQUIRED = 'WORKSPACE_NAME_REQUIRED',
  WORKSPACE_SLUG_REQUIRED = 'WORKSPACE_SLUG_REQUIRED',
  WORKSPACE_SLUG_ALREADY_EXISTS = 'WORKSPACE_SLUG_ALREADY_EXISTS',
  WORKSPACE_INVALID_TYPE = 'WORKSPACE_INVALID_TYPE',
  WORKSPACE_INVALID_PLAN = 'WORKSPACE_INVALID_PLAN',
  WORKSPACE_INVALID_STATUS = 'WORKSPACE_INVALID_STATUS',
  WORKSPACE_OWNER_REQUIRED = 'WORKSPACE_OWNER_REQUIRED',
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_ACCESS_DENIED = 'WORKSPACE_ACCESS_DENIED',
  WORKSPACE_MEMBER_NOT_FOUND = 'WORKSPACE_MEMBER_NOT_FOUND',
  WORKSPACE_MEMBER_ALREADY_EXISTS = 'WORKSPACE_MEMBER_ALREADY_EXISTS',
  WORKSPACE_MEMBER_INVALID_ROLE = 'WORKSPACE_MEMBER_INVALID_ROLE',
  WORKSPACE_MEMBER_INVALID_STATUS = 'WORKSPACE_MEMBER_INVALID_STATUS',
  WORKSPACE_ENTITY_MISMATCH = 'WORKSPACE_ENTITY_MISMATCH',
  WORKSPACE_REQUIRED = 'WORKSPACE_REQUIRED',
  PLAN_LIMIT_EXCEEDED = 'PLAN_LIMIT_EXCEEDED',
  OPPOSITION_WORKSPACE_REQUIRED = 'OPPOSITION_WORKSPACE_REQUIRED',
}
