// Codigos de error de usuarios, oposiciones y control de acceso (SPEC 010, 16).

export enum AccessErrorCode {
  // Usuario
  USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_PASSWORD_REQUIRED = 'USER_PASSWORD_REQUIRED',
  USER_INVALID_ROLE = 'USER_INVALID_ROLE',
  USER_INVALID_STATUS = 'USER_INVALID_STATUS',
  // Autenticacion / acceso
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  ADMIN_ACCESS_REQUIRED = 'ADMIN_ACCESS_REQUIRED',
  STUDENT_ACCESS_REQUIRED = 'STUDENT_ACCESS_REQUIRED',
  // Oposicion
  OPPOSITION_TITLE_REQUIRED = 'OPPOSITION_TITLE_REQUIRED',
  OPPOSITION_SLUG_REQUIRED = 'OPPOSITION_SLUG_REQUIRED',
  OPPOSITION_SLUG_ALREADY_EXISTS = 'OPPOSITION_SLUG_ALREADY_EXISTS',
  OPPOSITION_INVALID_STATUS = 'OPPOSITION_INVALID_STATUS',
  OPPOSITION_NOT_FOUND = 'OPPOSITION_NOT_FOUND',
  // Acceso a oposicion
  OPPOSITION_ACCESS_NOT_FOUND = 'OPPOSITION_ACCESS_NOT_FOUND',
  OPPOSITION_ACCESS_ALREADY_EXISTS = 'OPPOSITION_ACCESS_ALREADY_EXISTS',
  OPPOSITION_ACCESS_REVOKED = 'OPPOSITION_ACCESS_REVOKED',
  // Integridad de datos por oposicion
  OPPOSITION_REQUIRED = 'OPPOSITION_REQUIRED',
  OPPOSITION_ENTITY_MISMATCH = 'OPPOSITION_ENTITY_MISMATCH',
}
